export const boostDetails: string
export const card: string
export const container: string
export const content: string
export const footer: string
export const kiLogo: string
export const numberOfFights: string
export const price: string
export const text: string
export const title: string
