export const card: string
export const closeButton: string
export const cosmonContainer: string
export const cosmonData: string
export const cosmonNumber: string
export const floorPrice: string
export const modal: string
export const modalContent: string
export const modalTitle: string
export const overlay: string
export const priceInput: string
export const priceInputContainer: string
export const sellingPrice: string
export const submitButton: string
export const xki: string
export const xkiLabel: string
