export const active: string
export const arrow: string
export const btn: string
export const disabledColored: string
export const ghost: string
export const primary: string
export const primaryBordered: string
export const quaternary: string
export const reverse: string
export const secondary: string
export const small: string
export const white: string
