export const attrContent: string
export const attrIcon: string
export const boost: string
export const boostButton: string
export const boostIcon: string
export const container: string
export const content: string
export const leftBlock: string
export const price: string
export const rightBlock: string
export const selectedBoost: string
export const subtitle: string
export const title: string
