declare global {
  namespace NodeJS {
    interface ProcessEnv {
      NEXT_PUBLIC_IS_PRODUCTION?: string
      NEXT_PUBLIC_CHAIN_ID?: string
      NEXT_PUBLIC_IBC_CHAIN_ID?: string
      NEXT_PUBLIC_CHAIN_NAME?: string
      NEXT_PUBLIC_CHAIN_RPC_ENDPOINT?: string
      NEXT_PUBLIC_CHAIN_REST_ENDPOINT?: string
      NEXT_PUBLIC_IBC_CHAIN_RPC_ENDPOINT?: string
      NEXT_PUBLIC_IBC_CHAIN_REST_ENDPOINT?: string
      NEXT_PUBLIC_BIP_COIN_TYPE?: string
      NEXT_PUBLIC_STAKING_DENOM?: string
      NEXT_PUBLIC_STAKING_IBC_DENOM?: string
      NEXT_PUBLIC_DENOM?: string
      NEXT_PUBLIC_CHAIN_BECH32_PREFIX?: string
      NEXT_PUBLIC_IBC_CHAIN_BECH32_PREFIX?: string
      NEXT_PUBLIC_CHAIN_GECKO_ID?: string
      NEXT_PUBLIC_NFT_CONTRACT?: string
      NEXT_PUBLIC_SELL_CONTRACT?: string
      NEXT_PUBLIC_REWARDS_CONTRACT?: string
      NEXT_PUBLIC_WHITELIST_CONTRACT?: string
      NEXT_PUBLIC_DECK_CONTRACT?: string
      NEXT_PUBLIC_XP_REGISTRY_CONTRACT?: string
      NEXT_PUBLIC_TRAINING_CONTRACT?: string
      NEXT_PUBLIC_GAME_CONTRACT?: string
      NEXT_PUBLIC_MAILCHIMP_URL?: string
      NEXT_PUBLIC_YIELD_COMMON?: string
      NEXT_PUBLIC_YIELD_UNCOMMON?: string
      NEXT_PUBLIC_YIELD_RARE?: string
      NEXT_PUBLIC_YIELD_EPIC?: string
      NEXT_PUBLIC_YIELD_LEGENDARY?: string
      NEXT_PUBLIC_IBC_DENOM_RAW?: string
      NEXT_PUBLIC_IBC_DENOM_HUMAN?: string
      NEXT_PUBLIC_IBC_DENOM?: string
      NEXT_PUBLIC_IBC_TX_FEES?: string
      NEXT_PUBLIC_KICHAIN_TO_IBC_CHANNEL?: string
      NEXT_PUBLIC_IBC_TO_KICHAIN_CHANNEL?: string
      NEXT_PUBLIC_ARENA_IS_ACTIVE?: string
      NEXT_PUBLIC_SEARCH_BLOCKCHAIN_HEIGHT_STEPS?: string
      NEXT_PUBLIC_IS_ACTIVE_WALLET_CONNECT?: string
      NEXT_PUBLIC_IS_ACTIVE_MARKETPLACE?: string
    }
  }
}

export {}
