version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

restore_cache: &restore_cache
  restore_cache:
    keys:
      - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - yarn-cache-{{ .Branch }}- # Fallback in case checksum fails

save_cache: &save_cache
  save_cache:
    key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

jobs:
  test_and_build:
    docker:
      - image: circleci/node:14
    working_directory: ~/project
    steps:
      - checkout
      - <<: *restore_cache
      - run: yarn install
      - <<: *save_cache
      - run:
          name: yarn build
          command: |
            if [[ "$CIRCLE_BRANCH" == "main" ]]; then CI=false yarn build; else CI=false yarn build-preprod; fi
      - persist_to_workspace:
          root: out
          paths:
            - '*'

  deploy_preprod:
    docker:
      - image: cimg/aws:2023.01
    working_directory: ~/project
    steps:
      - aws-cli/setup:
          role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/circleci-cosmonwebsite-deploy"
      - attach_workspace:
          at: out
      - run:
          name: Add robots.txt, Deploy to S3 and clear cache
          command: |
            cd out
            echo -e 'User-Agent: *\nDisallow: /' > robots.txt
            aws s3 sync icons s3://${PREPROD_S3_BUCKET_NAME}/icons --cache-control max-age=31536000,public # 1y cache for icons files
            aws s3 sync . s3://${PREPROD_S3_BUCKET_NAME} --exclude 'icons/*' --cache-control max-age=60,public # 1min cache for others
            aws cloudfront create-invalidation --distribution-id ${PREPROD_CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
      - run:
          name: Send Slack notification
          command: |
            curl -X POST --data-urlencode "payload={\"channel\": \"#dev\", \"username\": \"Staging Deploy\", \"text\": \"It's time to test! https://cosmon.preprod.kifoundation.tech/ has been deployed to preprod successfully!\", \"icon_emoji\": \":airplane:\"}" ${SLACK_WEBHOOK_URL}

  deploy_prod:
    docker:
      - image: cimg/aws:2023.01
    working_directory: ~/project
    steps:
      - aws-cli/setup:
          role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/circleci-cosmonwebsite-deploy"
      - attach_workspace:
          at: out
      - run:
          name: Deploy to S3 and clear cache
          command: |
            cd out
            aws s3 sync icons s3://${PROD_S3_BUCKET_NAME}/icons --cache-control max-age=31536000,public # 1y cache for icons files
            aws s3 sync . s3://${PROD_S3_BUCKET_NAME} --exclude 'icons/*' --cache-control max-age=60,public # 1min cache for others
            aws cloudfront create-invalidation --distribution-id ${PROD_CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
      - run:
          name: Send Slack notification
          command: |
            curl -X POST --data-urlencode "payload={\"channel\": \"#dev\", \"username\": \"PROD Deploy\", \"text\": \"Yeah! https://cosmon.ki has been deployed to production successfully!\", \"icon_emoji\": \":rocket:\"}" ${SLACK_WEBHOOK_URL}

workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - test_and_build
      - deploy_preprod:
          context:
            - aws-preprod
            - deploy-notifications
          requires:
            - test_and_build
          filters:
            branches:
              only: 
                - preprod
                - preprod-new
      - deploy_prod:
          context:
            - aws-prod
            - deploy-notifications
          requires:
            - test_and_build
          filters:
            branches:
              only: main
