export const cardContainer: string
export const cosmonCard: string
export const cosmonListItem: string
export const cosmonListItemFooter: string
export const flip: string
export const flipButton: string
export const kiLogo: string
export const label: string
export const priceContainer: string
export const priceValue: string
