export const amount: string
export const borderShinyGradient: string
export const darkText: string
export const disabled: string
export const maxWAuto: string
export const partners: string
export const pill: string
export const primaryText: string
export const secondaryText: string
export const transferCardIcon: string
