export const amount: string
export const borderShinyGradient: string
export const cosmostationWcModal: string
export const darkText: string
export const disabled: string
export const maxWAuto: string
export const partners: string
export const pill: string
export const placeBottom: string
export const placeLeft: string
export const placeRight: string
export const placeTop: string
export const primaryText: string
export const reactComponentTooltip: string
export const secondaryText: string
export const transferCardIcon: string
