export const description: string
export const laterButton: string
export const modal: string
export const modalContent: string
export const modalTitle: string
export const overlay: string
export const submitButton: string
export const submitContainer: string
export const textInput: string
