export const collectionInfo: string
export const collectionTitle: string
export const floorPriceValue: string
export const floorPriceValueImg: string
export const floorPriceValueText: string
export const headerContainer: string
export const info: string
export const label: string
export const logo: string
export const separator: string
export const separatorContainer: string
export const value: string
