const EMAIL_COLLECTED_LOCAL_STORAGE_KEY = 'email-collected'
const EMAIL_LATER_COUNT_LOCAL_STORAGE_KEY = 'email-later-count'

export { EMAIL_COLLECTED_LOCAL_STORAGE_KEY, EMAIL_LATER_COUNT_LOCAL_STORAGE_KEY }
