const EMAIL_COLLECTED_LOCAL_STORAGE_KEY = 'email-collected'
const EMAIL_LATER_COUNT_LOCAL_STORAGE_KEY = 'email-later-count'
const IS_MARKETPLACE_ACTIVE: boolean =
  process.env.NEXT_PUBLIC_IS_ACTIVE_MARKETPLACE !== '0' ?? false

export {
  EMAIL_COLLECTED_LOCAL_STORAGE_KEY,
  EMAIL_LATER_COUNT_LOCAL_STORAGE_KEY,
  IS_MARKETPLACE_ACTIVE,
}
