export const attributeItem: string
export const attributeLabel: string
export const attributesGrid: string
export const attributValue: string
export const buyButton: string
export const buyButtonContainer: string
export const cardAttributes: string
export const cardDetails: string
export const cardPrice: string
export const cardPriceTitle: string
export const container: string
export const cosmonCard: string
export const cosmonLabel: string
export const cosmonOwner: string
export const cosmonOwnerWallet: string
export const headerAttribute: string
export const kiLogo: string
export const labelDetails: string
export const linePrice: string
export const priceLabel: string
export const priceUsdc: string
export const priceValue: string
export const rightContainer: string
export const titleAttributes: string
export const titleDetails: string
export const valueDetails: string
