export const backCosmonImg: string
export const button: string
export const card: string
export const closeButton: string
export const confetti: string
export const cosmonName: string
export const description: string
export const flipCosmon: string
export const flipCosmonRevealed: string
export const labelNotRevealed: string
export const modal: string
export const modalContent: string
export const overlay: string
export const revealedCosmon: string
export const scarcity: string
export const title: string
