export const container: string
export const from: string
export const fromCol: string
export const hash: string
export const hashCol: string
export const label: string
export const link: string
export const price: string
export const row: string
export const tabIcon: string
export const table: string
export const title: string
export const to: string
export const toCol: string
export const type: string
export const typeCol: string
