export const activeButton: string
export const button: string
export const buttonMargin: string
export const chevron: string
export const clearFilterButton: string
export const container: string
export const filterHeader: string
export const filtersContainer: string
export const filterSide: string
export const header: string
export const levelFilter: string
export const listContainer: string
export const loadingContainer: string
export const nameInput: string
export const optionsContainer: string
export const personnalityFilter: string
export const priceFilter: string
export const scarcityFilter: string
export const selectOptionsSortOrder: string
export const selectPrefix: string
export const selectSortOrder: string
export const submitContainer: string
export const submitFilterButton: string
export const timeFilter: string
