export const activeButton: string
export const button: string
export const buttonMargin: string
export const container: string
export const header: string
export const loadingContainer: string
export const optionsContainer: string
export const paginationButton: string
export const paginationContainer: string
