export const chartContainer: string
export const common: string
export const cosmonStatsCardContainer: string
export const divinity: string
export const epic: string
export const legendary: string
export const mainContainer: string
export const rare: string
export const statsContainer: string
export const title: string
export const uncommon: string
export const xpProgressionContainer: string
