export const attributsContainer: string
export const cosmonCardContainer: string
export const flag: string
export const label: string
export const level: string
export const lg: string
export const md: string
export const scarcityContainer: string
export const sm: string
