export const card: string
export const closeButton: string
export const cosmonCard: string
export const cosmonData: string
export const cosmonNumber: string
export const experienceContainer: string
export const level: string
export const modal: string
export const price: string
export const tipsText: string
export const title: string
