export const card: string
export const closeButton: string
export const cosmonCard: string
export const cosmonData: string
export const cosmonNumber: string
export const experienceContainer: string
export const label: string
export const level: string
export const modal: string
export const price: string
export const secondLabel: string
export const statsContainer: string
export const statsLine: string
export const statsLineSeparation: string
export const thxText: string
export const title: string
export const value: string
export const xp: string
export const xpBarre: string
export const xpBarreContainer: string
export const xpBold: string
