export const container: string
export const defeatIcon: string
export const drawIcon: string
export const defeatLine: string
export const doughnut: string
export const doughnutContent: string
export const legendContent: string
export const legendLabel: string
export const value: string
export const victoryIcon: string
export const victoryLine: string
