export const combatLimit: string
export const combatLimitCounter: string
export const combatLimitMessage: string
export const combatLimitOverlay: string
export const countdown: string
export const fire: string
export const missFpBoldMessage: string
export const missFpMessage: string
export const missFpOverlay: string
